### ISSUE TITLE
Milestone 3 To Do

### ISSUE THREAD

**Issue by alyciakb** [UBC-MDS/running_late#12]
**Final Write Up**
- [x] Survey topic Introduction (Sreya)
- [x] Write up analysis section and link to code file (Aaron)
- [x] Visualizations (Alycia)
- [x] Survey study design section (causality, what we did well, what we can do better) (Fan)
- [x] Compile, edit, concluding remarks

**Other Tasks**
- [x] Finish analysis (Aaron)
- [x] Update proposal to address Kate's milestone 1 issues
- [x] Update EDA to include next steps
- [x] Update README
